--1
SELECT PLAYERS.PLAYERNO,NAME, INITIALS, COUNT(WON) FROM PLAYERS, MATCHES WHERE PLAYERS.PLAYERNO = MATCHES.PLAYERNO GROUP BY PLAYERS.PLAYERNO, NAME, INITIALS;
--2
SELECT NAME, PEN_DATE, AMOUNT FROM PENALTIES,PLAYERS WHERE PLAYERS.PLAYERNO = PENALTIES.PLAYERNO ORDER BY AMOUNT ASC;
--3
SELECT TEAMNO, NAME FROM TEAMS, PLAYERS WHERE TEAMS.PLAYERNO = PLAYERS.PLAYERNO;
--4
SELECT NAME, WON, LOST FROM PLAYERS,MATCHES WHERE PLAYERS.PLAYERNO = MATCHES.PLAYERNO AND WON>LOST;
--5
SELECT PLAYERS.PLAYERNO, PLAYERS.NAME, SUM(AMOUNT) FROM PLAYERS,PENALTIES WHERE PLAYERS.PLAYERNO = PENALTIES.PLAYERNO GROUP BY PLAYERS.PLAYERNO, PLAYERS.NAME; 
--6
SELECT LOC FROM EMP,DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO AND ENAME ='ALLEN';
--7
SELECT * FROM EMP E WHERE SAL > (SELECT SAL FROM EMP WHERE EMPNO = E.MGR);
--8
SELECT COUNT(*),EXTRACT(YEAR FROM TO_DATE(HIREDATE,'DD-MM-YYYY'))  FROM EMP GROUP BY EXTRACT(YEAR FROM TO_DATE(HIREDATE,'DD-MM-YYYY'));
--9
SELECT * FROM EMP WHERE JOB IN (SELECT JOB FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO'));