--Übung 3 SQL
--1
SELECT PLAYERNO,NAME FROM PLAYERS WHERE YEAR_OF_BIRTH > 1960;
--2
SELECT PLAYERNO,NAME,TOWN FROM PLAYERS WHERE SEX = 'F' AND NOT TOWN = 'Stratford';
--3
SELECT PLAYERNO 
FROM PLAYERS 
WHERE YEAR_OF_BIRTH BETWEEN 1970 AND 1980;
--4
SELECT PLAYERNO, NAME, YEAR_OF_BIRTH 
FROM PLAYERS
WHERE (MOD(YEAR_OF_BIRTH,4)=0 AND NOT MOD(YEAR_OF_BIRTH,100)=0) 
OR (MOD(YEAR_OF_BIRTH,100)=0 AND NOT MOD(YEAR_OF_BIRTH,400)=0) 
OR MOD(YEAR_OF_BIRTH,400)=0;
--5
SELECT PAYMENTNO 
FROM PENALTIES 
WHERE AMOUNT BETWEEN 50 AND 100;
--6
SELECT PLAYERNO,NAME 
FROM PLAYERS 
WHERE NOT TOWN IN ('Douglas','Stratford');
--7
SELECT PLAYERNO, NAME 
FROM PLAYERS 
WHERE NAME LIKE '%is%';
--8
SELECT * 
FROM PLAYERS 
WHERE LEAGUENO IS NULL;



-- EMP DEPT
--9
SELECT * 
FROM EMP 
WHERE COMM > SAL;
--10
SELECT * 
FROM EMP 
WHERE DEPTNO = 30 AND SAL >=1500;
--11
SELECT MGR 
FROM EMP 
WHERE NOT DEPTNO = 30;
--12
SELECT * 
FROM EMP 
WHERE JOB NOT IN ('CLERK','MANAGER');
--13
SELECT * 
FROM EMP 
WHERE SAL BETWEEN 1200 AND 1300;
--14 
SELECT * 
FROM EMP 
WHERE ENAME LIKE 'ALL__';
--15 
SELECT COMM+SAL 
FROM EMP 
WHERE COMM IS NOT NULL;
--16
SELECT * 
FROM EMP 
WHERE 1.25*COMM > SAL;
--17
SELECT AVG(SAL) 
FROM EMP 
WHERE JOB = 'CLERK' GROUP BY JOB;
--18
SELECT COUNT(*) 
FROM EMP 
WHERE COMM IS NOT NULL;
--19
SELECT COUNT(JOB) 
FROM EMP 
WHERE DEPTNO = 30;
--20
SELECT COUNT(*) 
FROM EMP 
WHERE DEPTNO = 30;
--21
SELECT * 
FROM EMP 
WHERE HIREDATE BETWEEN '04.01.1981' AND '15.04.1981';