--1
SELECT DISTINCT NAME
FROM PLAYERS
JOIN MATCHES ON PLAYERS.PLAYERNO = MATCHES.PLAYERNO
WHERE MATCHES.PLAYERNO IN (
    SELECT PLAYERNO
    FROM MATCHES
    GROUP BY PLAYERNO
    HAVING COUNT(distinct TEAMNO) > 1
)
--2
SELECT NAME, INITIALS
FROM PLAYERS
WHERE PLAYERNO NOT IN (
    SELECT PLAYERNO
    FROM PENALTIES
    WHERE extract(YEAR from PEN_DATE) = 1980
)
--3
SELECT *
FROM PLAYERS
WHERE PLAYERNO IN (
    SELECT PLAYERNO
    FROM PENALTIES
    WHERE AMOUNT > 80
)
--Falsch aber verlockend (weil Spieler mehfrach gelistet werden):
SELECT *
FROM PLAYERS
JOIN PENALTIES ON PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
WHERE AMOUNT > 80
--4
SELECT *
FROM PLAYERS
WHERE PLAYERNO IN (
    SELECT PLAYERNO
    FROM PENALTIES
    GROUP BY PLAYERNO
    HAVING MIN(AMOUNT) > 80
)
--5
SELECT *
FROM EMP e1
JOIN DEPT ON e1.DEPTNO = DEPT.DEPTNO
WHERE SAL > (
    SELECT AVG(SAL)
    FROM EMP e2
    WHERE e2.DEPTNO = e1.DEPTNO
)
--6
SELECT *
FROM DEPT
WHERE DEPTNO IN (
    SELECT DISTINCT DEPTNO
    FROM EMP
)
--7
SELECT *
FROM DEPT
WHERE DEPTNO IN (
    SELECT DISTINCT DEPTNO
    FROM EMP
    WHERE SAL > 1000
)
--8
SELECT *
FROM DEPT
WHERE DEPTNO NOT IN (
    SELECT DISTINCT DEPTNO
    FROM EMP
    WHERE SAL < 1000
)
