--1
SELECT TEAMNO FROM TEAMS WHERE NOT PLAYERNO = 27;
--2
SELECT PLAYERS.PLAYERNO, NAME, INITIALS FROM PLAYERS,MATCHES WHERE MATCHES.PLAYERNO = PLAYERS.PLAYERNO AND MATCHES.WON >=1;
--3
SELECT PLAYERS.PLAYERNO, NAME FROM PLAYERS, PENALTIES WHERE PENALTIES.PLAYERNO = PLAYERS.PLAYERNO;
--4
SELECT PLAYERS.PLAYERNO, NAME FROM PLAYERS,PENALTIES WHERE PENALTIES.PLAYERNO = PLAYERS.PLAYERNO AND AMOUNT > 50; 
--5
SELECT PLAYERNO,NAME FROM PLAYERS WHERE YEAR_OF_BIRTH = (SELECT YEAR_OF_BIRTH FROM PLAYERS WHERE NAME = 'Parmenter' AND INITIALS ='R');
--6
SELECT PLAYERNO, NAME FROM PLAYERS WHERE YEAR_OF_BIRTH = (SELECT MAX(YEAR_OF_BIRTH) FROM PLAYERS);
--7
SELECT DEPTNO FROM DEPT MINUS SELECT DEPTNO FROM EMP GROUP BY DEPTNO;
--8
SELECT * FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'JONES');
--9
SELECT * FROM EMP WHERE SAL > (SELECT MIN(SAL) FROM EMP WHERE DEPTNO = 30);
--10
SELECT * FROM EMP WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 30);
--11 
SELECT * FROM EMP WHERE DEPTNO = 10 AND NOT JOB IN (SELECT JOB FROM EMP WHERE DEPTNO = 30);
--12 
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);